### PR TITLE
Update MissionControlView.java

### PR DESCRIPTION
**Pull request by jaggs6**
Fixes `feature%2Fhello` job name to appear as `feature/hello`

### CODE REVIEW

**Comment by jaggs6** [comment]
Fixed in #1

**Comment by jaggs6** [comment]
Actually Not really fixed in the latest release. I will test this and come back with update

**Comment by a-shevtsov** [comment]
Wondering whether you had time to look into this? If not, I can close this PR and you can reopen it when you can provide more details.

**Comment by jaggs6** [comment]
Sorry. Will test it tomorrow

**Pull request closed without merging**
